version: "3.9"

services:
  api:
    image: "node:14"
    ports:
      - "4000:4000"
    volumes: 
      - ./:/opt/app
    working_dir: "/opt/app"
    command: bash -c "npm start"
    networks:
      - restaurant-network
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.0.31"
    ports: 
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
    volumes:
      - restaurant-volume:/var/lib/mysql
    networks:
      - restaurant-network

volumes:
  restaurant-volume:

networks:
  restaurant-network:
    driver: bridge
